network_id: test
node_config:
  - node_id: will
    poll_rate: 10
    retry: 3
    url: http://hh70a6nnqcg.sn.mynetname.net:8000/
  - node_id: ripple
    poll_rate: 10
    retry: 3
    url: http://wan.ripplefcl.com:8000
  - node_id: chkgay
    poll_rate: 10
    retry: 3
    url: http://wan.ripplefcl.com:8000
  - node_id: jens
    poll_rate: 10
    retry: 3
    url: http://meshmon.jensens.eu:8000
  - node_id: dagger
    poll_rate: 10
    retry: 3
    url: http://server-01.hanrahan.cloud:8000
